# Generated by Django 2.1.3 on 2018-11-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
