# Generated by Django 2.1.3 on 2018-11-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181119_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
